/** Declaration file generated by dts-gen */

export = dotenv_expand;

declare function dotenv_expand(config: any): any;

declare namespace dotenv_expand {
    const prototype: {
    };

}

